doc-dev:
	cd ./zh/docs && npm run start

doc-build:
	cd ./zh/docs && npm run build

doc-serve:
	cd ./zh/docs && npm run serve

docker-build:
	docker build  . --no-cache -t chrissong1994/7xdoc-typeorm:latest --platform linux/amd64,linux/arm64
